version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
  nginx:
    depends_on:
      - user
      - feed
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./reverseproxy
    ports:
      - "3051:80"
  user:
    build:
      dockerfile: Dockerfile
      context: ./api-user
    volumes:
      - /app/node_modules
      - ./api-user:/app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
  feed:
    build:
      dockerfile: Dockerfile
      context: ./api-feed
    volumes:
      - /app/node_modules
      - ./api-feed:/app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
