name: udacity-project-3
on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Feed
        uses: docker/build-push-action@v2
        id: docker_build_feed
        with:
          context: ./api-feed
          file: ./api-feed/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-api-feed

      - name: Build and Push USER
        uses: docker/build-push-action@v2
        id: docker_build_user
        with:
          context: ./api-user
          file: ./api-user/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-api-user

      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        id: docker_build_fronend
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/udagram-frontend

      - name: Build and Push Reverseproxy
        uses: docker/build-push-action@v2
        id: docker_build_reverseproxy
        with:
          context: ./reverseproxy
          file: ./reverseproxy/Dockerfile
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/reverseproxy

      - name: Verify
        run: echo ${{steps.docker_build_reverseproxy.outputs.digest}}
